Repository dkpro/dkpro-jwpl, pull requests merged in 2023-10, with the labels that each got.

#231 #24 - Automatically delete *.bin files after dump creation process
  de.tudarmstadt.ukp.wikipedia.datamachine/src/main/java/de/tudarmstadt/ukp/wikipedia/datamachine/dump/xml/SimpleBinaryDumpWriter.java
  de.tudarmstadt.ukp.wikipedia.datamachine/src/main/java/de/tudarmstadt/ukp/wikipedia/datamachine/file/DeleteFilesAtShutdown.java
Labels: 🆕Enhancement

#250 #249 Remove commons-codec dependency in favor of JDK's own Base64 codec
  dkpro-jwpl-revisionmachine/pom.xml
  dkpro-jwpl-revisionmachine/src/main/java/org/dkpro/jwpl/revisionmachine/difftool/data/codec/RevisionDecoder.java
  dkpro-jwpl-revisionmachine/src/main/java/org/dkpro/jwpl/revisionmachine/difftool/data/codec/RevisionEncoder.java
Labels: dependencies

#253 #241 Update dependency Spring to version 6.x
  .github/workflows/maven.yml
  dkpro-jwpl-wikimachine/pom.xml
  dkpro-jwpl-wikimachine/src/main/java/org/dkpro/jwpl/wikimachine/factory/SpringFactory.java
  pom.xml
Labels: dependencies

#258 #257 - Add issue templates
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/refactoring.md
  .github/pull_request_template.md
  .gitignore
Labels: ⚙️Refactoring

#256 Fixes #255: Missing license.txt files
  dkpro-jwpl-deps/LICENSE.txt
  dkpro-jwpl-deps/dkpro-jwpl-swc-engine-shade/LICENSE.txt
  dkpro-jwpl-mwdumper/LICENSE.txt
  dkpro-jwpl-wikimachine/LICENSE.txt
Labels: ⚙️Refactoring

#262 #261 - Clean up POMs
  dkpro-jwpl-api/pom.xml
  dkpro-jwpl-datamachine/pom.xml
  dkpro-jwpl-parser/pom.xml
  dkpro-jwpl-revisionmachine/pom.xml
  dkpro-jwpl-timemachine/pom.xml
  dkpro-jwpl-tutorial/pom.xml
  dkpro-jwpl-util/pom.xml
  dkpro-jwpl-wikimachine/pom.xml
  pom.xml
Labels: ⚙️Refactoring
