Repository dkpro/dkpro-jwpl, pull requests merged in 2023-11, with the labels that each got.

#266 #261 - Clean up POMs
  dkpro-jwpl-api/pom.xml
  dkpro-jwpl-deps/dkpro-jwpl-swc-engine-shade/pom.xml
  dkpro-jwpl-revisionmachine/pom.xml
  dkpro-jwpl-util/pom.xml
  dkpro-jwpl-wikimachine/pom.xml
  pom.xml
Labels: ⚙️Refactoring

#272 #124 PageQueryIterable doesn't escape special characters
  dkpro-jwpl-api/src/main/java/org/dkpro/jwpl/api/PageQueryIterable.java
  dkpro-jwpl-api/src/test/java/org/dkpro/jwpl/api/PageIteratorTest.java
  dkpro-jwpl-api/src/test/java/org/dkpro/jwpl/api/PageQueryIterableTest.java
  dkpro-jwpl-api/src/test/java/org/dkpro/jwpl/api/TitleIteratorTest.java
  dkpro-jwpl-api/src/test/resources/db/wikiapi_test.properties
  dkpro-jwpl-api/src/test/resources/db/wikiapi_test.script
Labels: 🆕Enhancement, test

#275 #274 Delete setting Hibernate dialects at compile-time in WikiHibernateUtil
  dkpro-jwpl-api/src/main/java/org/dkpro/jwpl/api/hibernate/WikiHibernateUtil.java
Labels: ⚙️Refactoring

#283 Resolves "Reviewer feedback for 2.0.0 RC1"
  dkpro-jwpl-api/pom.xml
  dkpro-jwpl-api/src/it/java/org/dkpro/jwpl/api/PerformanceTest.java
  dkpro-jwpl-api/src/main/java/org/dkpro/jwpl/api/CategoryGraph.java
  dkpro-jwpl-api/src/main/java/org/dkpro/jwpl/api/Page.java
  dkpro-jwpl-api/src/main/java/org/dkpro/jwpl/api/PageQueryIterable.java
  dkpro-jwpl-api/src/main/java/org/dkpro/jwpl/api/WikiConstants.java
  dkpro-jwpl-api/src/main/java/org/dkpro/jwpl/api/Wikipedia.java
  dkpro-jwpl-api/src/main/java/org/dkpro/jwpl/api/WikipediaInfo.java
  dkpro-jwpl-api/src/main/java/org/dkpro/jwpl/api/sweble/PlainTextConverter.java
  dkpro-jwpl-api/src/main/java/org/dkpro/jwpl/api/sweble/TemplateNameExtractor.java
  dkpro-jwpl-api/src/main/java/org/dkpro/jwpl/api/util/ApiUtilities.java
  dkpro-jwpl-api/src/main/java/org/dkpro/jwpl/api/util/CommonUtilities.java
  dkpro-jwpl-api/src/main/java/org/dkpro/jwpl/api/util/DbUtilities.java
  dkpro-jwpl-api/src/main/java/org/dkpro/jwpl/api/util/GraphUtilities.java
  dkpro-jwpl-api/src/main/java/org/dkpro/jwpl/api/util/HibernateUtilities.java
  dkpro-jwpl-api/src/main/java/org/dkpro/jwpl/api/util/OS.java
  dkpro-jwpl-api/src/main/java/org/dkpro/jwpl/api/util/StringUtils.java
  dkpro-jwpl-api/src/main/java/org/dkpro/jwpl/api/util/UnmodifiableArraySet.java
  dkpro-jwpl-api/src/main/java/org/dkpro/jwpl/api/util/distance/LevenshteinStringDistance.java
  dkpro-jwpl-api/src/main/java/org/dkpro/jwpl/api/util/distance/StringDistance.java
  dkpro-jwpl-api/src/test/java/org/dkpro/jwpl/api/WikiConfigTest.java
  dkpro-jwpl-deps/dkpro-jwpl-swc-engine-shade/NOTICE.txt
  dkpro-jwpl-deps/dkpro-jwpl-swc-engine-shade/pom.xml
  dkpro-jwpl-revisionmachine/README
  dkpro-jwpl-revisionmachine/src/main/resources/configSamples/diffTool_config_sample.xml
  dkpro-jwpl-revisionmachine/src/main/resources/configSamples/indexGenerator_config_sample
  dkpro-jwpl-revisionmachine/src/test/resources/db/wikiapi_simple_20090119_stripped.script
  dkpro-jwpl-util/NOTICE.txt
  dkpro-jwpl-util/pom.xml
  dkpro-jwpl-util/src/main/java/org/dkpro/jwpl/util/templates/generator/simple/WikipediaTemplateInfoGenerator.java
  dkpro-jwpl-util/src/main/java/org/dkpro/jwpl/util/templates/parser/ParseUtils.java
  dkpro-jwpl-util/src/main/java/org/dkpro/jwpl/util/templates/parser/SectionExtractor.java
Labels: 🆕Enhancement, 📖Documentation
